steps:
  # ==========================================
  # 1. Build and Push Frontend
  # ==========================================
  - name: 'gcr.io/cloud-builders/docker'
    args: 
      - 'build'
      - '--no-cache'
      - '--build-arg'
      - 'VITE_API_URL=https://ai-productivity-benchmark-backend-csyt6j5toa-ue.a.run.app/api'
      - '-t'
      - 'gcr.io/$PROJECT_ID/ai-productivity-benchmark-frontend'
      - '.'
  
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/ai-productivity-benchmark-frontend']

  # ==========================================
  # 2. Build and Push Backend
  # ==========================================
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/ai-productivity-benchmark-backend', './backend']
  
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/ai-productivity-benchmark-backend']

  # ==========================================
  # Note: Python Agent Service runs locally with stdio transport
  # It is not deployed to Cloud Run
  # ==========================================

  # ==========================================
  # 4. Deploy Backend (NestJS)
  # ==========================================
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'ai-productivity-benchmark-backend'
      - '--image'
      - 'gcr.io/$PROJECT_ID/ai-productivity-benchmark-backend'
      - '--region'
      - 'us-east1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--add-cloudsql-instances'
      - 'nice-opus-478203-b3:us-east1:ai-productivity-db'
      - '--port'
      - '3000'
      - '--set-env-vars'
      - 'DATABASE_URL=$_DATABASE_URL,GEMINI_API_KEY=$_GEMINI_API_KEY,JWT_SECRET=$_JWT_SECRET,GOOGLE_CLIENT_ID=$_GOOGLE_CLIENT_ID,GOOGLE_CLIENT_SECRET=$_GOOGLE_CLIENT_SECRET,GOOGLE_CALLBACK_URL=$_GOOGLE_CALLBACK_URL,FRONTEND_URL=$_FRONTEND_URL'



  # ==========================================
  # 3. Deploy Frontend
  # ==========================================
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'ai-productivity-benchmark-frontend'
      - '--image'
      - 'gcr.io/$PROJECT_ID/ai-productivity-benchmark-frontend'
      - '--region'
      - 'us-east1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'

images:
  - 'gcr.io/$PROJECT_ID/ai-productivity-benchmark-frontend'
  - 'gcr.io/$PROJECT_ID/ai-productivity-benchmark-backend'

substitutions:
  _DATABASE_URL: ''
  _GEMINI_API_KEY: ''
  _JWT_SECRET: ''
  _GOOGLE_CLIENT_ID: ''
  _GOOGLE_CLIENT_SECRET: ''
  _GOOGLE_CALLBACK_URL: ''
  _FRONTEND_URL: ''
